
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameTextField1 = new javax.swing.JTextField();
        AsadButton1 = new javax.swing.JButton();
        IdTextField2 = new javax.swing.JTextField();
        RafiButton2 = new javax.swing.JButton();
        jShafiButton3 = new javax.swing.JButton();
        PostTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SumonButton4 = new javax.swing.JButton();
        BackButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        WorkingTimeTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NameTextField1.setEditable(false);
        NameTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NameTextField1.setText("ID");

        AsadButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AsadButton1.setText("ASAD");
        AsadButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsadButton1ActionPerformed(evt);
            }
        });

        IdTextField2.setEditable(false);
        IdTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IdTextField2.setText("Name");

        RafiButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RafiButton2.setText("Rafi");
        RafiButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RafiButton2ActionPerformed(evt);
            }
        });

        jShafiButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jShafiButton3.setText("Shafi");
        jShafiButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShafiButton3ActionPerformed(evt);
            }
        });

        PostTextField3.setEditable(false);
        PostTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PostTextField3.setText("Post");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Employee");

        SumonButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SumonButton4.setText("Sumon");
        SumonButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumonButton4ActionPerformed(evt);
            }
        });

        BackButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BackButton5.setText("Back");
        BackButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Clear All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        WorkingTimeTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WorkingTimeTextField1.setText("Working Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SumonButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AsadButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(RafiButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jShafiButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(WorkingTimeTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BackButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(NameTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IdTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PostTextField3, javax.swing.GroupLayout.Alignment.LEADING))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AsadButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RafiButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PostTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jShafiButton3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SumonButton4)
                        .addComponent(jButton1))
                    .addComponent(WorkingTimeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(BackButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AsadButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsadButton1ActionPerformed
        employee ASAD= new employee("155555","MD ASAD","Senior manager","10AM-6AM");  //object create and value pass..md
        
        IdTextField2.setText(ASAD.id);
        NameTextField1.setText(ASAD.name);
        PostTextField3.setText(ASAD.post);
        WorkingTimeTextField1.setText(ASAD.workingHour);
    }//GEN-LAST:event_AsadButton1ActionPerformed

    private void RafiButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RafiButton2ActionPerformed
      employee Rafi= new employee("166665","MD Rafi","manager","8AM-4PM");
        
        IdTextField2.setText(Rafi.id);
        NameTextField1.setText(Rafi.name);
        PostTextField3.setText(Rafi.post);
        WorkingTimeTextField1.setText(Rafi.workingHour);
    }//GEN-LAST:event_RafiButton2ActionPerformed

    private void jShafiButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShafiButton3ActionPerformed
        employee Shafi= new employee("177775","MD Shafi","Salesman","8AM-12PM");
        
        IdTextField2.setText(Shafi.id);
        NameTextField1.setText(Shafi.name);
        PostTextField3.setText(Shafi.post);
        WorkingTimeTextField1.setText(Shafi.workingHour);
// TODO add your handling code here:
    }//GEN-LAST:event_jShafiButton3ActionPerformed

    private void SumonButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumonButton4ActionPerformed
       employee Sumon= new employee("188885","MD Sumon","salesman","8AM-12PM");
        
        IdTextField2.setText(Sumon.id);
        NameTextField1.setText(Sumon.name);
        PostTextField3.setText(Sumon.post); 
        WorkingTimeTextField1.setText(Sumon.workingHour);
    }//GEN-LAST:event_SumonButton4ActionPerformed

    private void BackButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton5ActionPerformed
     Mframe11 f1= new Mframe11();
      f1.setVisible(true);
         dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_BackButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     IdTextField2.setText(null);
     NameTextField1.setText(null);
     PostTextField3.setText(null);
     WorkingTimeTextField1.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsadButton1;
    private javax.swing.JButton BackButton5;
    private javax.swing.JTextField IdTextField2;
    private javax.swing.JTextField NameTextField1;
    private javax.swing.JTextField PostTextField3;
    private javax.swing.JButton RafiButton2;
    private javax.swing.JButton SumonButton4;
    private javax.swing.JTextField WorkingTimeTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jShafiButton3;
    // End of variables declaration//GEN-END:variables
}
